import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#005C6D',
        width: '100%'
    },
    topHome: {
        backgroundColor: '#005C6D',
        width: '100%',
        marginBottom: 16,
        paddingBottom: 16,
        borderBottomRightRadius: 24,
        borderBottomLeftRadius: 24,
    },
    logoContainer: {
        alignItems: "flex-end",
    },
    logo: {
        marginTop: 40,
        width: 100,
        height: 100,
        resizeMode: "contain",
        marginBottom: 24,
    },
    greeting: {
        color: '#f7f8fa',
        fontSize: 18,
        marginBottom: 10,
        marginRight: 24,
        paddingHorizontal: 24,
        fontFamily: 'PlusJakartaSans_600SemiBold',
    },
    title: {
        color: '#f7f8fa',
        fontSize: 32,
        fontWeight: 'bold',
        marginBottom: 24,
        paddingHorizontal: 24,
        fontFamily: 'PlusJakartaSans_700Bold',
    },
    subtitle: {
        color: '#f7f8fa',
        fontSize: 24,
        marginBottom: 36,
        marginRight: 14,
        paddingHorizontal: 24,
        fontFamily: 'PlusJakartaSans_400Regular',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: "space-between",
        borderRadius: 28,
        borderColor: '#D1D5D8',
        borderWidth: 1,
        backgroundColor: '#E4E9EB',
        padding: 8,
        paddingHorizontal: 16,
        marginTop: 42,
        marginBottom: 16,
        width: '90%',
        minHeight: 40,
        alignSelf: 'center',
        maxWidth: '100%',
    },
    searchText: {
        color: '#000',
        fontSize: 14,
        flexShrink: 1,
        flex: 1,
        fontFamily: 'PlusJakartaSans_400Regular',
    },
    examsText:{
        marginTop: 48,
        marginBottom: 16,
        marginLeft: 24,
        alignSelf: 'flex-start',
        color: '#666666',
        fontSize: 16,
        fontFamily: 'PlusJakartaSans_600SemiBold',
    }
});