import { StyleSheet } from 'react-native';

const bottomNavHeight = 80;

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F4F8F7' },
  scrollContent: { paddingHorizontal: 0 },
  profileCard: {
   backgroundColor: '#005C6D',
    borderRadius: 20,
    paddingTop: 30,
    paddingBottom: 40,
    // marginTop: 20, // remova esta linha!
    marginBottom: 10,
    elevation: 3,
    zIndex: 2,
    position: 'relative',
    overflow: 'visible',
    width: '100%',
  },
  profileCardContent: {
    paddingHorizontal: 20,
    width: '100%',
  },
  editButton: {
    position: 'absolute',
    top: 18,
    right: 18,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#B2EBF2',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#fff',
    zIndex: 4,
  },
  editButtonText: { marginLeft: 5, color: '#020202ff', fontWeight: 'bold' },
  avatarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 40,
    minHeight: 120,
  },
  avatarWrapper: {
    position: 'absolute',
    left: 5,
    bottom: -70,
    zIndex: 5,
    elevation: 5,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#B2EBF2',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  name: {
    top:60,
    marginLeft: 135,
    fontSize: 24,
    fontWeight: 'normal',
    color: '#fff',
    flex: 1,
    alignSelf: 'center',
  },
  optionsCard: {
    backgroundColor: '#F4F8F7',
    borderRadius: 15,
    marginTop: 60,
    overflow: 'hidden',
    elevation: 2,
    zIndex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  optionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 18 },
  optionText: { fontSize: 16, color: '#004A5A', fontWeight: 'bold' },
  logoutText: { fontSize: 16, color: '#D32F2F', fontWeight: 'bold' },
  divider: { height: 1, backgroundColor: '#DDDDDD', marginHorizontal: 0 },
  rankingSection: { marginTop: 30, paddingHorizontal: 20 },
  rankingTitle: { fontSize: 28, fontWeight: 'bold', color: '#00839A' },
  rankingDescription: { fontSize: 15, color: '#585858', marginTop: 10, lineHeight: 22 },
  rankingList: { marginTop: 20 },
  rankingItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  rankingNumber: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#004A5A', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  rankingNumberText: { color: '#fff', fontWeight: 'bold' },
  rankingItemText: { fontSize: 18, color: '#333', flex: 1 },
  rankingAcertos: { fontSize: 16, color: '#004A5A', fontWeight: 'bold' },
  bottomNav: { height: bottomNavHeight },

  // Modal
  modalContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },
  modalContent: { width: '85%', backgroundColor: '#fff', borderRadius: 15, padding: 20, alignItems: 'center' },
  modalTitle: { fontSize: 22, fontWeight: 'bold', marginBottom: 20 },
  modalAvatar: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#B2EBF2', justifyContent: 'center', alignItems: 'center', marginBottom: 15 },
  input: { width: '100%', borderWidth: 1, borderColor: '#ccc', borderRadius: 10, padding: 10, marginBottom: 20 },
  saveButton: { backgroundColor: '#00839A', paddingVertical: 12, paddingHorizontal: 30, borderRadius: 10, marginBottom: 10 },
  saveButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  cancelButton: { backgroundColor: '#ccc', paddingVertical: 12, paddingHorizontal: 30, borderRadius: 10 },
  cancelButtonText: { color: '#333', fontSize: 16, fontWeight: 'bold' },

  // Modal Termos
  termsContent: { width: '85%', backgroundColor: '#fff', borderRadius: 15, padding: 20, alignItems: 'center' },
  termsText: { fontSize: 15, color: '#333', marginBottom: 20, textAlign: 'justify' },
});