import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex:1, padding:20, backgroundColor:'#f7f8fa', justifyContent:'center', alignItems:'center' },
  logoContainer: { justifyContent:'center', alignItems:'center', marginBottom:20, position:'relative' },
  circleBg : { position:'absolute', width: 240, height: 220, resizeMode:'contain', zIndex:0 },
  logo: { width:220, height:200, resizeMode: 'contain', zIndex: 1 },
  title: { fontSize:24, fontWeight:'bold', textAlign:'center', marginBottom:8, color:'#005C6D' },
  subtitle: { fontSize:16, textAlign:'center', marginBottom:45, color:'#1b1b1bff' },
  buttonRow: { flexDirection:'row', justifyContent:'space-between', marginHorizontal:20 },
  button: { flex:1, paddingVertical:14, borderRadius:60, marginHorizontal:5, alignItems:'center' },
  loginButton: { backgroundColor:'#005C6D' },
  registerButton: { borderWidth:1, borderColor:'#005C6D', backgroundColor:'transparent' },
  buttonText: { fontSize:16 },
  loginText: { color:'#f7f8fa' },
  registerText: { color:'#233D4D' },
  input: { borderWidth:1, borderColor:'#CCC', borderRadius:6, padding:12, marginBottom:12 },
  inputRow: { flexDirection:'row', alignItems:'center', marginBottom:12 },
  eyeIcon: { position:'absolute', right:12 },
  submitButton: { backgroundColor:'#233D4D', paddingVertical:14, borderRadius:6, alignItems:'center', marginVertical:16 },
  submitText: { color:'#f7f8fa', fontSize:16 },
  dividerRow: { flexDirection:'row', alignItems:'center', marginVertical:16 },
  divider: { flex:1, height:1, backgroundColor:'#CCC' },
  dividerText: { marginHorizontal:8, color:'#555' },
  googleButton: { flexDirection:'row', alignItems:'center', justifyContent:'center', borderWidth:1, borderColor:'#CCC', padding:12, borderRadius:6 },
  googleText: { marginLeft:8, color:'#555' },
  bottomText: { textAlign:'center', color:'#555' },
  linkText: { color:'#2D5CA7', fontWeight:'bold' },
});
