export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  Inicial: undefined;
  Login: undefined;
  Cadastro: undefined;
  Home: undefined;
  Vida: undefined;
  Ranking: undefined;
  Conquista: { acertos: number, faseConcluida?: number };
  ExameConquista: { acertos: number};
  Perfil: undefined;
  Mapa: { faseConcluida?: number } | undefined;
  Materia: { nome: string; assuntos: string[] };
  Desafio: undefined;
  Quiz: { tempoTotal: number; tempoAtivado: boolean, faseAtual: number };
  Termos: undefined;
  DecidirTempo: { semestre: string };
  Exames: { semestre: string; tempoAtivado: boolean; tempoTotal: number }; 
  Prova: { semestre: string; questoes: number };
  Main: undefined;
};